### ISSUE TITLE
Avatar Download

### ISSUE THREAD

**Issue by symptog** [okfde/2013.archiv.codefor.de#50]
das Pythonscript mag es nicht, wenn da ein Member keinen Namen hat. Vielleicht kann man das ja abfangen.

DEBUG:root:Processing Lab giessen/index.html
DEBUG:root:Processing Lab Member None
DEBUG:root:Checking github for None
Traceback (most recent call last):
  File "download_avatars.py", line 55, in <module>
    main()
  File "download_avatars.py", line 45, in main
    image_url = get_image(username)
  File "download_avatars.py", line 14, in get_github
    response = requests.get('https://api.github.com/users/' + username)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by symptog** [comment]
fixed
